In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

In [58]:
data = pd.read_csv("data.csv")
test = pd.read_csv("test.csv")
data.columns = ["age", "workclass", "fnlwgt", "education", "education-num", "marital-status", "occupation", "relationship", "race", "sex", "capital-gain", "capital-loss", "hours-per-week", "native-country", "income"]
test.columns = ["age", "workclass", "fnlwgt", "education", "education-num", "marital-status", "occupation", "relationship", "race", "sex", "capital-gain", "capital-loss", "hours-per-week", "native-country", "income"]
dataset = pd.concat([data, test], ignore_index=True)


In [59]:
cat = ["workclass", "education", "marital-status", "occupation", "relationship", "race", "sex", "native-country"]
df = pd.DataFrame(columns=cat)
for col in cat:
    LEnc = LabelEncoder()
    tmp = LEnc.fit_transform(dataset[col])
    df[col] = tmp
    print(tmp)
    
OHEnc = OneHotEncoder(sparse=False)
tmp = OHEnc.fit_transform(df)
cont = ['age', 'fnlwgt', 'education-num', 'capital-gain', 'capital-loss', 'hours-per-week', 'income']
enc_dataset = pd.concat([pd.DataFrame(tmp, columns=[str(i) for i in range(tmp.shape[1])]), dataset[cont]], axis=1)

[6 4 4 ... 4 4 5]
[ 9 11  1 ...  9  9  9]
[2 0 2 ... 2 0 2]
[ 4  6  6 ... 10  1  4]
[0 1 0 ... 0 3 0]
[4 4 2 ... 4 1 4]
[1 1 1 ... 1 1 1]
[39 39 39 ... 39 39 39]


In [61]:
tmp.shape

(48840, 102)

In [62]:
enc_dataset['income'].value_counts()

 <=50K     24719
 <=50K.    12434
 >50K       7841
 >50K.      3846
Name: income, dtype: int64

In [63]:
#LEnc = LabelEncoder()
#tmp = LEnc.fit_transform(dataset[col])
enc_dataset['income'] = enc_dataset['income'].str.replace('<=50K.', '1')
enc_dataset['income'] = enc_dataset['income'].str.replace('<=50K', '1')
enc_dataset['income'] = enc_dataset['income'].str.replace('>50K.', '0')
enc_dataset['income'] = enc_dataset['income'].str.replace('>50K', '0')

In [64]:
enc_dataset['income'].value_counts()

 1    37153
 0    11687
Name: income, dtype: int64

In [65]:
enc_dataset.to_csv('train+test.csv')

In [17]:
tmp.shape

(48840, 106)

In [31]:
dataset['income'].value_counts()

 <=50K     24719
 <=50K.    12434
 >50K       7841
 >50K.      3846
Name: income, dtype: int64

In [29]:
enc_dataset['105'].value_counts()

0.0    44994
1.0     3846
Name: 105, dtype: int64

In [63]:
to_encode = dataset.drop(['age', 'fnlwgt', 'education-num', 'capital-gain', 'capital-loss', 'hours-per-week'], axis=1)
pure_data = dataset.drop(["workclass", "education", "marital-status", "occupation", "relationship", "race", "sex", "native-country", "income"], axis=1)
for col_name in to_encode.columns:
    l_enc = LabelEncoder()
    to_encode[col_name] = pd.DataFrame(l_enc.fit_transform(to_encode[col_name]))
    oh_enc = OneHotEncoder()
    
    print(to_encode[col_name].values)
    
    encoded = pd.DataFrame(oh_enc.fit_transform(to_encode[col_name].values.reshape(-1, 1)))
    pure_data = pd.concat([pure_data, encoded_data], axis = 1)

[6 4 4 ... 4 4 4]


c:\python36\lib\site-packages\sklearn\preprocessing\_encoders.py:363: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


ValueError: DataFrame constructor not properly called!

In [42]:
test

age          workclass  fnlwgt      education  education-num  \
0       38            Private   89814        HS-grad              9   
1       28          Local-gov  336951     Assoc-acdm             12   
2       44            Private  160323   Some-college             10   
3       18                  ?  103497   Some-college             10   
4       34            Private  198693           10th              6   
5       29                  ?  227026        HS-grad              9   
6       63   Self-emp-not-inc  104626    Prof-school             15   
7       24            Private  369667   Some-college             10   
8       55            Private  104996        7th-8th              4   
9       65            Private  184454        HS-grad              9   
10      36        Federal-gov  212465      Bachelors             13   
11      26            Private   82091        HS-grad              9   
12      58                  ?  299831        HS-grad              9   
13      48            Private  279724        HS-grad              9   
14      43            Private  346189        Masters             14   
15      20          State-gov  444554   Some-college             10   
16      43            Private  128354        HS-grad              9   
17      37            Private   60548        HS-grad              9   
18      40            Private   85019      Doctorate             16   
19      34            Private  107914      Bachelors             13   
20      34            Private  238588   Some-college             10   
21      72                  ?  132015        7th-8th              4   
22      25            Private  220931      Bachelors             13   
23      25            Private  205947      Bachelors             13   
24      45   Self-emp-not-inc  432824        HS-grad              9   
25      22            Private  236427        HS-grad              9   
26      23            Private  134446        HS-grad              9   
27      54            Private   99516        HS-grad              9   
28      32   Self-emp-not-inc  109282   Some-college             10   
29      46          State-gov  106444   Some-college             10   
...    ...                ...     ...            ...            ...   
16250   81                  ?   26711      Assoc-voc             11   
16251   60            Private  117909      Assoc-voc             11   
16252   39            Private  229647      Bachelors             13   
16253   38            Private  149347        Masters             14   
16254   43          Local-gov   23157        Masters             14   
16255   23            Private   93977        HS-grad              9   
16256   73       Self-emp-inc  159691   Some-college             10   
16257   35            Private  176967   Some-college             10   
16258   66            Private  344436        HS-grad              9   
16259   27            Private  430340   Some-college             10   
16260   40            Private  202168    Prof-school             15   
16261   51            Private   82720        HS-grad              9   
16262   22            Private  269623   Some-college             10   
16263   64   Self-emp-not-inc  136405        HS-grad              9   
16264   50          Local-gov  139347        Masters             14   
16265   55            Private  224655        HS-grad              9   
16266   38            Private  247547      Assoc-voc             11   
16267   58            Private  292710     Assoc-acdm             12   
16268   32            Private  173449        HS-grad              9   
16269   48            Private  285570        HS-grad              9   
16270   61            Private   89686        HS-grad              9   
16271   31            Private  440129        HS-grad              9   
16272   25            Private  350977        HS-grad              9   
16273   48          Local-gov  349230        Masters             14   
16274   33            Private  